### ISSUE TITLE
获取登录地址失败

### ISSUE THREAD

**Issue by Codgi-123** [blackyau/luci-app-suselogin#1]
如图：
![image](https://user-images.githubusercontent.com/54504858/110333744-f0c94180-805c-11eb-8041-ab1ddb9788e2.png)

**Comment by blackyau** [comment]
先检查已经连接到这个路由器的设备，能不能打开认证页面。如果不能打开，那就是网络设置有问题
如果可以打开的话，就用路由器执行
```shell
curl -s "http://www.google.cn/generate_204"
```
看看返回结果是什么

**Comment by Codgi-123** [comment]
蟹蟹学长，已经解决了XD
